<a href="https://colab.research.google.com/github/JAtoms/neuralearn/blob/main/tensor_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
one_d = tf.constant([2,0,-3,8,90])
print(one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [4]:
two_d = tf.constant([
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
     ]
    )
print(two_d.ndim)

2


In [5]:
three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

])

print(three_d.shape)

(4, 2, 3)


In [6]:
four_d = tf.constant([
    [
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],
    ],

    [
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],
    ],

])

print(four_d.shape)
print(four_d.ndim)
four_casted = tf.cast(four_d, dtype = tf.bool)
print(four_casted)

(2, 4, 2, 3)
4
tf.Tensor(
[[[[ True  True False]
   [ True  True  True]]

  [[ True  True False]
   [ True False  True]]

  [[ True  True False]
   [ True  True False]]

  [[ True  True  True]
   [ True  True  True]]]


 [[[ True  True False]
   [ True  True  True]]

  [[ True  True False]
   [ True False  True]]

  [[ True  True False]
   [ True  True False]]

  [[ True  True  True]
   [ True  True  True]]]], shape=(2, 4, 2, 3), dtype=bool)


In [7]:
import numpy as np

In [8]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [9]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [10]:
# Identity matrix
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [11]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [12]:
# Identity matrix
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=5,
    batch_shape=[4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor*3)

tf.Tensor(
[[[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]]

 [[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]]

 [[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]]

 [[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]]], shape=(4, 3, 5), dtype=float32)


In [13]:
fill_tensor = tf.fill(
    [3,4], 5, name=None, layout=None
)

print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [14]:
tensor_ones = tf.ones(
    [4,3,2],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(tensor_ones)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(4, 3, 2), dtype=float32)


In [15]:
tensor_ones_like = tf.ones_like(
    fill_tensor, dtype=None, name=None, layout=None
)

print(tensor_ones_like)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [16]:
# two_d = tf.constant([
#     [1,2,0],
#      [3,5,-1],
#       [1,5,6],
#        [2,3,8]
#      ]
#     )


print(three_d[0:2, 0, :])

tf.Tensor(
[[ 1  2  0]
 [10  2  0]], shape=(2, 3), dtype=int32)


In [17]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [18]:
x_1 = tf.constant([
         [3,5,-1],
       [2,3,8]
])
x_2 = tf.constant([
          [3,5,-1],
           [3,5,-1],
       [2,3,8]
])

tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 22,  37, -16],
       [ 31,  49,  59]], dtype=int32)>

## Matrice Multiplication

In [21]:
A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

B = np.array([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5],
])

np.matmul(A,B)

array([[33, 69, 77, -6, 27],
       [ 9, 12,  0, 10, 13],
       [21, 51, 60, -7, 14]])

## Einsum Multiplication
Einsum multiplication handles matmul, transpose and element wise multiplication

In [23]:
A = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

B = np.array([
    [2,9,0,3],
    [3,6,8,-2],
    [1,3,5,0]
])

np.einsum( 'ij,ij -> ij',A,B)

array([[  4,  54,   0,   6],
       [  6, -12,  16,  -6],
       [  1,  15,  20,   0]])

In [32]:
A = np.array([

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]],

    [[2,6,5,2],
     [2,-2,2,3],
     [1,5,4,0]]
    ])
B = np.array([
    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]],

    [[2,9,0,3,0],
     [3,6,8,-2,2],
     [1,3,5,0,1],
     [3,0,2,0,5]]
])

print(A.shape, B.shape)

# np.matmul(A,B)
np.einsum('bij,bjk -> bik', A,B)

(2, 3, 4) (2, 4, 5)


array([[[33, 69, 77, -6, 27],
        [ 9, 12,  0, 10, 13],
        [21, 51, 60, -7, 14]],

       [[33, 69, 77, -6, 27],
        [ 9, 12,  0, 10, 13],
        [21, 51, 60, -7, 14]]])