<a href="https://colab.research.google.com/github/JAtoms/neuralearn/blob/main/tensor_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
one_d = tf.constant([2,0,-3,8,90])
print(one_d)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
two_d = tf.constant([
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
     ]
    )
print(two_d.ndim)

2


In [ ]:
three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],

])

print(three_d.shape)

(4, 2, 3)


In [ ]:
four_d = tf.constant([
    [
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],
    ],

    [
    [[1,2,0],
    [3,5,-1]],

    [[10,2,0],
    [1,0,2]],

    [[5,8,0],
    [2,7,0]],

    [[2,1,9],
    [4,-3,32]],
    ],

])

print(four_d.shape)
print(four_d.ndim)
four_casted = tf.cast(four_d, dtype = tf.bool)
print(four_casted)

(2, 4, 2, 3)
4
tf.Tensor(
[[[[ True  True False]
   [ True  True  True]]

  [[ True  True False]
   [ True False  True]]

  [[ True  True False]
   [ True  True False]]

  [[ True  True  True]
   [ True  True  True]]]


 [[[ True  True False]
   [ True  True  True]]

  [[ True  True False]
   [ True False  True]]

  [[ True  True False]
   [ True  True False]]

  [[ True  True  True]
   [ True  True  True]]]], shape=(2, 4, 2, 3), dtype=bool)


In [ ]:
import numpy as np

In [ ]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [ ]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [ ]:
# Identity matrix
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [ ]:
# Identity matrix
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=5,
    batch_shape=[4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor*3)

tf.Tensor(
[[[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]]

 [[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]]

 [[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]]

 [[3. 0. 0. 0. 0.]
  [0. 3. 0. 0. 0.]
  [0. 0. 3. 0. 0.]]], shape=(4, 3, 5), dtype=float32)


In [ ]:
fill_tensor = tf.fill(
    [3,4], 5, name=None, layout=None
)

print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
tensor_ones = tf.ones(
    [4,3,2],
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
print(tensor_ones)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(4, 3, 2), dtype=float32)


In [ ]:
tensor_ones_like = tf.ones_like(
    fill_tensor, dtype=None, name=None, layout=None
)

print(tensor_ones_like)

tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)


In [ ]:
# two_d = tf.constant([
#     [1,2,0],
#      [3,5,-1],
#       [1,5,6],
#        [2,3,8]
#      ]
#     )


print(three_d[0:2, 0, :])

tf.Tensor(
[[ 1  2  0]
 [10  2  0]], shape=(2, 3), dtype=int32)


In [ ]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [ ]:
x_1 = tf.constant([
         [3,5,-1],
       [2,3,8]
])
x_2 = tf.constant([
          [3,5,-1],
           [3,5,-1],
       [2,3,8]
])

tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 22,  37, -16],
       [ 31,  49,  59]], dtype=int32)>